[package]
name = "pysniff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rsniffa"
crate-type = ["cdylib"]

[dependencies]
address = "0.9.0"
etherparse = "0.14.3"
pcap = "2.0.0"
pyo3 = "0.20.0"
